### ISSUE TITLE
Where is FBnegLossCompute?

### ISSUE THREAD

**Issue by rzhao1** [stanfordnlp/cocoa#49]

**Comment by hhexiy** [comment]
That's not needed. Removed in the latest commit. Thanks for catching it!

**Comment by rzhao1** [comment]
Thank you! Sorry, I got another error when run dealornodeal code:

Vocab not found at mappings/lf2lf/vocab.pkl
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    data_generator = get_data_generator(args, model_args, schema)
  File "/home/ranzhao1/Documents/cocoa/dealornodeal/neural/__init__.py", line 32, in get_data_generator
    model=model_args.model)
  File "/home/ranzhao1/Documents/cocoa/dealornodeal/neural/preprocess.py", line 360, in __init__
    self.mappings = self.load_mappings(model, mappings_path, schema, preprocessor)
  File "/home/ranzhao1/Documents/cocoa/dealornodeal/neural/preprocess.py", line 382, in load_mappings
    preprocessor.entity_forms.values())
  File "/home/ranzhao1/Documents/cocoa/dealornodeal/neural/vocab_builder.py", line 30, in create_mappings
    utterance_vocab = build_utterance_vocab(dialogues, sequence_markers, entity_forms)
  File "/home/ranzhao1/Documents/cocoa/cocoa/neural/vocab_builder.py", line 24, in build_utterance_vocab
    for dialogue in dialogues:
TypeError: 'NoneType' object is not iterable
